
package com.babel.rent.test.ws.port;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RentWS", targetNamespace = "http://ws.rent.babel.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RentWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.babel.rent.test.ws.port.Rent
     */
    @WebMethod
    @WebResult(partName = "return")
    public Rent createRent(
        @WebParam(name = "arg0", partName = "arg0")
        Rent arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.babel.rent.test.ws.port.Rent
     */
    @WebMethod
    @WebResult(partName = "return")
    public Rent readRent(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.babel.rent.test.ws.port.Rent
     */
    @WebMethod
    @WebResult(partName = "return")
    public Rent saveRent(
        @WebParam(name = "arg0", partName = "arg0")
        Rent arg0);

}
