
package com.babel.rent.test.ws.port;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RentWSService", targetNamespace = "http://ws.rent.babel.com/", wsdlLocation = "http://localhost:8080/rent-ws/Rent?wsdl")
public class RentWSService
    extends Service
{

    private final static URL RENTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException RENTWSSERVICE_EXCEPTION;
    private final static QName RENTWSSERVICE_QNAME = new QName("http://ws.rent.babel.com/", "RentWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/rent-ws/Rent?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RENTWSSERVICE_WSDL_LOCATION = url;
        RENTWSSERVICE_EXCEPTION = e;
    }

    public RentWSService() {
        super(__getWsdlLocation(), RENTWSSERVICE_QNAME);
    }

    public RentWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RENTWSSERVICE_QNAME, features);
    }

    public RentWSService(URL wsdlLocation) {
        super(wsdlLocation, RENTWSSERVICE_QNAME);
    }

    public RentWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RENTWSSERVICE_QNAME, features);
    }

    public RentWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RentWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RentWS
     */
    @WebEndpoint(name = "RentWSPort")
    public RentWS getRentWSPort() {
        return super.getPort(new QName("http://ws.rent.babel.com/", "RentWSPort"), RentWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RentWS
     */
    @WebEndpoint(name = "RentWSPort")
    public RentWS getRentWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.rent.babel.com/", "RentWSPort"), RentWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RENTWSSERVICE_EXCEPTION!= null) {
            throw RENTWSSERVICE_EXCEPTION;
        }
        return RENTWSSERVICE_WSDL_LOCATION;
    }

}
